// Generated by https://quicktype.io

export interface DalleInterfaces {
    created: number;
    data?:    Datum[];
    credits: number;
    creator: any
    prompt:  string;
    cloudinarySave: string | { url: string; public_id: string; };
}

export interface Datum {
    url: string;
}
