declare module '*.jpg';
declare module '*.png';
declare module '*.jpeg';
declare module '*.webp';
declare module '*.svg';
declare module '*.gif';
declare module '*.mp4';
declare module '*.mp3';
declare module 'webp-converter';